### ISSUE TITLE
[Issue]: Is the google_autocomplete field required in the database?

### ISSUE THREAD

**Issue by dallen-aupe** [TappNetwork/filament-google-autocomplete-field#4]
### What happened?

Following the directions on the Filament website, I am able to get the field working correctly with no issues. However when I submit, I get:

```
Unknown column 'google_autocomplete' in 'field list'
```

Here is my form code:

```php
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                TextInput::make('name')->required(),

                GoogleAutocomplete::make('google_search')
                    ->label('Search address')
                    ->countries([
                        'CA',
                    ])
                    ->withFields([
                        TextInput::make('address_1')
                            ->required()
                            ->extraInputAttributes([
                                'data-google-field' => '{street_number} {route}',
                            ]),
                        TextInput::make('city')
                            ->required()
                            ->extraInputAttributes([
                                'data-google-field' => 'locality',
                            ]),
                        TextInput::make('province')
                            ->required()
                            ->extraInputAttributes([
                                'data-google-field' => 'administrative_area_level_1',
                            ]),
                        TextInput::make('postal_code')
                            ->required()
                            ->extraInputAttributes([
                                'data-google-field' => 'postal_code',
                            ]),
                        TextInput::make('lat')
                            ->nullable()
                            ->extraInputAttributes([
                                'data-google-field' => 'latitude',
                            ]),
                        TextInput::make('lng')
                            ->nullable()
                            ->extraInputAttributes([
                                'data-google-field' => 'longitude',
                            ]),
                    ]),
            ]);
    }
```

If I add a new database field called `google_autocomplete`, it will let me submit but then it includes some random string like `ChIJBRMtddGaLIgR00H4ryxYrb0`.

![CleanShot 2024-07-29 at 10 18 12@2x](https://github.com/user-attachments/assets/1329382e-6e4f-4c13-a7a1-0f884e600bce)

Not sure what I've done wrong here, any help would be appreciated :)

### How to reproduce the bug

See above.

### Package Version

1.01

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by andreia** [comment]
@dallen-aupe Thank you for reporting! :)

I was trying to replicate (I used the same fields as in your example) but it's not requiring the select field for me. 

<img width="1195" alt="Screen Shot 2024-08-03 at 17 18 47" src="https://github.com/user-attachments/assets/c904e804-63ef-4cb1-ad64-aeceaf85ce66">

The `User` model I used for testing has only `id` guarded:

```php
protected $guarded = [
    'id',
];
```

Anyway,  the `google_autocomplete` select field should be prevented from being dehydrated. Created this PR https://github.com/TappNetwork/filament-google-autocomplete-field/pull/5 adding  `->dehydrated(false)`. Please let me know if it works for you
